vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = 'crashplan'
  config.vm.provision "shell", path: "./crashplan_server.sh"

end