# objective: create a vagrant instance that runs docker

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "splunkserver"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provision "shell", path: "./splunk_enterprise.sh"

end
