vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.hostname = 'ror'
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.provision(:shell, path: './ruby_on_rails_install.sh')

end
