vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.hostname = 'ror'
  # port 3000 is the default port for "Puma" - the built-in Rails Web Server
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.vm.provision(:shell, path: './ruby_on_rails_install.sh')

end
