# objective: create a vagrant instance that contains and can run salt

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "./bootstrap.sh"

end
