---

AWSTemplateFormatVersion: 2010-09-09

Description: AWS CloudFormation Stack for Running ElasticBeanstalk.

Parameters: {}

Mappings: {}

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  PublicInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicInternetRouteTable

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicInternetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.0.0.0/25
      VpcId: !Ref VPC

  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.0.0.128/25
      VpcId: !Ref VPC

  PublicSubnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicInternetRouteTable
      SubnetId: !Ref PublicSubnet01

  PublicSubnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicInternetRouteTable
      SubnetId: !Ref PublicSubnet02
  
  # this SecurityGroup can be:
  # added as the _only_ security group for ElasticBeanstalk EC2 instances
  # added in addition to the default ElasticBeanstalk Security Group for EC2 instances
  # in this particular case, we supplement the default ElasticBeanstalk Security Group
  # to allow port 22 in from world (you may not wish to do this in your own environment)
  # or you may wish to create the group and 
  ElasticBeanstalkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ElasticBeanstalkSecurityGroup
      GroupDescription: Security Group for all ElasticBeanstalk Environments
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC
  
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      # note that if ApplicationName is set and is not unique you
      # will not able able to run a given stack multiple times
      ApplicationName: !Ref AWS::StackName

  ElasticBeanstalkQAIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier

  ElasticBeanstalkQAInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles: 
        - !Ref ElasticBeanstalkQAIAMRole

  ElasticBeanstalkQAConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: 1
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: 1
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref ElasticBeanstalkQAInstanceProfile
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.micro
        - Namespace: aws:autoscaling:trigger
          OptionName: MeasureName
          # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalingtrigger
          Value: CPUUtilization
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref VPC
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          # Value: !Join turns the individual subnets into a string
          Value: !Join [ ",", [ !Ref PublicSubnet01, !Ref PublicSubnet02 ] ]
        - Namespace: aws:autoscaling:launchconfiguration
          # OptionName: SecurityGroups includes additional security groups
          # that will be added to EC2 instances in the Auto Scaling Group
          # that supports the Elastic Beanstalk application
          OptionName: SecurityGroups
          Value: !Ref ElasticBeanstalkSecurityGroup
        - Namespace: aws:ec2:vpc
          OptionName: AssociatePublicIpAddress
          Value: true
      SolutionStackName: 64bit Amazon Linux 2 v3.0.2 running PHP 7.4
  
  ElasticBeanstalkQAEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      Description: ElasticBeanstalk Environment for QA
      # EnvironmentName must be greater than or equal to 4 (you can't use "QA")
      EnvironmentName: !Sub ${AWS::StackName}-QA
      # TemplateName: with environments where every element is exactly the same
      # you may be able to use a single AWS::ElasticBeanstalk::ConfigurationTemplate
      TemplateName: !Ref ElasticBeanstalkQAConfigurationTemplate

  # ElasticBeanstalkProdIAMRole:
  #   Type: AWS::IAM::Role
  #   Properties: 
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: ec2.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns: 
  #       - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
# 
  # ElasticBeanstalkProdInstanceProfile:
  #   Type: AWS::IAM::InstanceProfile
  #   Properties: 
  #     Roles: 
  #       - !Ref ElasticBeanstalkProdIAMRole
# 
  # ElasticBeanstalkProdConfigurationTemplate:
  #   Type: AWS::ElasticBeanstalk::ConfigurationTemplate
  #   Properties:
  #     ApplicationName: !Ref ElasticBeanstalkApplication
  #     OptionSettings:
  #       - Namespace: aws:autoscaling:asg
  #         OptionName: MinSize
  #         Value: 1
  #       - Namespace: aws:autoscaling:asg
  #         OptionName: MaxSize
  #         Value: 1
  #       - Namespace: aws:autoscaling:launchconfiguration
  #         OptionName: InstanceType
  #         Value: t3.micro
  #       - Namespace: aws:autoscaling:launchconfiguration
  #         OptionName: IamInstanceProfile
  #         Value: !Ref ElasticBeanstalkProdInstanceProfile
  #       - Namespace: aws:autoscaling:trigger
  #         OptionName: MeasureName
  #         # # Only one aws:autoscaling:trigger allowed
  #         # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalingtrigger
  #         Value: CPUUtilization
  #       - Namespace: aws:elasticbeanstalk:environment
  #         OptionName: EnvironmentType
  #         Value: LoadBalanced
  #       - Namespace: aws:ec2:vpc
  #         OptionName: VPCId
  #         Value: !Ref VPC
  #       - Namespace: aws:ec2:vpc
  #         OptionName: Subnets
  #         # Value: !Join turns the individual subnets into a string
  #         Value: !Join [ ",", [ !Ref PublicSubnet01, !Ref PublicSubnet02 ] ]
  #       - Namespace: aws:autoscaling:launchconfiguration
  #         # OptionName: SecurityGroups includes additional security groups
  #         # that will be added to EC2 instances in the Auto Scaling Group
  #         # that supports the Elastic Beanstalk application
  #         OptionName: SecurityGroups
  #         Value: !Ref ElasticBeanstalkSecurityGroup
  #       - Namespace: aws:ec2:vpc
  #         OptionName: AssociatePublicIpAddress
  #         Value: true
  #     SolutionStackName: 64bit Amazon Linux 2 v3.0.2 running PHP 7.4
# 
  # ElasticBeanstalkProdEnvironment:
  #   Type: AWS::ElasticBeanstalk::Environment
  #   Properties:
  #     ApplicationName: !Ref ElasticBeanstalkApplication
  #     Description: AWS ElasticBeanstalk Environment for Prod
  #     # EnvironmentName must be greater than or equal to 4 (you can't use "QA")
  #     EnvironmentName: !Sub ${AWS::StackName}-Prod
  #     # TemplateName: with environments where every element is exactly the same
  #     # you may be able to use a single AWS::ElasticBeanstalk::ConfigurationTemplate
  #     TemplateName: !Ref ElasticBeanstalkProdConfigurationTemplate

Outputs: {}