vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/wily64'
  config.vm.provision "shell", path: "./vagrant_only.sh"
  config.vm.provision "shell", path: "./shared.sh"

end
