vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'tftpd'
  config.vm.network 'public_network'
  config.vm.provision(:shell, path: './install_tftpd-hpa_server.sh')

end
