vagrantfile_api_version = 2

Vagrant.configure(vagrantfile_api_version) do |config|

  # there are multiple Vagrant versions of Amazon Linux 2 available
  # in the Vagrant Box "Cloud" repository
  config.vm.box = 'bento/amazonlinux-2'
  config.vm.provision(:shell, path: './shell_provision_script.sh')

end
