vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'openvpnas'
  config.vm.network "private_network", ip: "192.168.2.2"
  config.vm.provision(:shell, path: './openvpn_access_server.sh')

end
