AWSTemplateFormatVersion: '2010-09-09'

Description: Creates an IAM Role linked to an IAM Policy with AWS S3 full access.

Resources:

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: S3StackManagerRole

  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3StackManagerPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource: '*'
      Roles:
        - !Ref IAMRole