vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'elastalert'

  # port forwarding for elasticsearch
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  config.vm.provision(:shell, path: './deploy.sh')

end
