vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.hostname = 'openldapserver'
  config.vm.provision 'shell', path: './openldap_unattended_install.sh'

end
