service: serverless-with-python3-parameter-store

provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  # note that the variable here will be exposed via the AWS Console
  environment:
    MY_API_KEY: ${ssm:my_api_key}

functions:
  hello:
    handler: handler.hello

