vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'

  config.vm.hostname = 'logdna'
  config.vm.provision 'shell', path: './logdna_config.sh', env: { LOGDNA_KEY: ENV['LOGDNA_KEY'] }

end
