vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.hostname = 'postgres'
  config.vm.provision(:shell, path: './basic_postgres_install.sh')

end
