vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = 'sidekiq'

  config.vm.provision(:shell, path: './basic_sidekiq_worker.sh')

end
