vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/trusty64'

  config.vm.hostname = 'solr'
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision(:shell, path: './solr_single_instance.sh')

end
