vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = 'jenkins'

  config.vm.provision(:shell, path: './jenkins_build.sh')
  config.vm.network :forwarded_port, guest: 8080, host: 8080

end
