vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/xenial64'

  config.vm.hostname = 'nginxproxy'
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.provision(:shell, path: './nginx_proxy_pass.sh')

end
