vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "docker"
  config.vm.provision "shell", path: "./docker_port_range_publish.sh"
  config.vm.network "private_network", ip: "192.168.2.2"

end
