vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.define "zookeeper" do |zookeeper|
    zookeeper.vm.box = "ubuntu/trusty64"
    zookeeper.vm.hostname = 'zookeeper'
    zookeeper.vm.provision(:shell, path: './zookeeper_instance.sh')
  end

end
