vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.provision "shell" do |s|
    s.env = {
      NEWRELIC_LICENSE_KEY: ENV['NEWRELIC_LICENSE_KEY'],
    }
  s.path = './install_newrelic_logging.sh'
  end

end
