vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "archiva"
  config.vm.network "private_network", ip: "192.168.2.2"

  config.vm.provision(:shell, path: "./archiva_basic_install_mysql.sh")

end
