# objective: create a vagrant instance running tomcat

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/wily64"
  config.vm.hostname = "tomcat"
  config.vm.provision "shell", path: "./basic_tomcat.sh"
  config.vm.network :forwarded_port, guest: 8080, host: 8080

end
