vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "kotlin"

  config.vm.provider "virtualbox" do |v|
    # v.memory = 1024
    v.cpus = 2
  end


  config.vm.provision(:shell, path: "./kotlin_compile_run_java.sh")
  # disable synced folder to _slightly_ improve test performance
  # config.vm.synced_folder ".", "/vagrant", disabled: true

end
