vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "bento/centos-7.2"
  config.vm.hostname = 'jinjaloop'
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./ansible/initial_playbook.yml"
  end

end
