# objective: create a vagrant instance that runs docker

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "docker"
  config.vm.provision "shell", path: "./docker_test_networking.sh"

end
