vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'elg'

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  # port forwarding for grafana
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  # port forwarding for elasticsearch
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  config.vm.provision(:shell, path: './deploy.sh')

end
