vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = 'mysql'
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision(:shell, path: './mysql_basic_install.sh')

end
