vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "centos/7"

  config.vm.hostname = 'crashplan'
  config.vm.provision "shell", path: "./crashplan_server.sh"

  config.vm.network "forwarded_port", guest: 4280, host: 4280
  config.vm.network "forwarded_port", guest: 4282, host: 4282
  config.vm.network "forwarded_port", guest: 4283, host: 4283
  config.vm.network "forwarded_port", guest: 4285, host: 4285
  config.vm.network "forwarded_port", guest: 4286, host: 4286


end
