VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = 'https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'
  # when jenkins package is available on trusty, move to new Vagrant image
  'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.hostname = 'jenkins'
  config.vm.network "private_network", ip: "192.168.50.2"

  config.vm.provider :virtualbox do |vb|
    vb.customize(['modifyvm', :id, '--memory', '2048'])
  end

  config.vm.provision(:shell, path: './jenkins_build.sh')
  config.vm.network :forwarded_port, guest: 8080, host: 8080

end