VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = 'jenkins'
  config.vm.network "private_network", ip: "192.168.2.2"

  config.vm.provider :virtualbox do |vb|
    vb.customize(['modifyvm', :id, '--memory', '2048'])
  end

  config.vm.provision(:shell, path: './jenkins_build.sh')
  config.vm.network :forwarded_port, guest: 8080, host: 8080

end
