vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.hostname = 'openvpnce'
  config.vm.network 'private_network', ip: '192.168.2.2'
  config.vm.provision(:shell, path: './openvpn_community_edition_ldap_foxpass.sh')

end
