#!/bin/bash -

AWS_DEV_ACCESS_KEY="AKWMNLRLSXQUKPRYUELL"
AWS_STG_ACCESS_KEY="AKRCESAQWTFQWJLHTQAU"

ENV="DEV"

AWS_ACCESS_KEY_VARIABLE=AWS_${ENV}_ACCESS_KEY
AWS_GENERATED_ACCESS_KEY=${!AWS_ACCESS_KEY_VARIABLE}
echo $AWS_GENERATED_ACCESS_KEY

ENV="STG"

AWS_ACCESS_KEY_VARIABLE=AWS_${ENV}_ACCESS_KEY
AWS_GENERATED_ACCESS_KEY=${!AWS_ACCESS_KEY_VARIABLE}
echo $AWS_GENERATED_ACCESS_KEY
