deploy-dev:
# worth understanding why ${} or $() should be used
# $() is used most commonly
	echo "Deploying $(ENVIRONMENT)"
	echo "This is $(AWS_PROFILE)"

deploy-prod:
# worth understanding why ${} or $() should be used
# $() is used most commonly
	echo "Deploying $(ENVIRONMENT)"
	echo "This is $(AWS_PROFILE)"
