# objective: create a vagrant instance that runs docker

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/wily64"
  config.vm.hostname = "sqoop"
  config.vm.provision "shell", path: "./basic_sqoop.sh"

end
