service: serverless-with-python3-secrets-manager

variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  # note that the variable here will be exposed via the AWS Console
  environment:
    MY_API_KEY: ${ssm:aws/reference/secretsmanager/snippets/serverless_framework/plaintext/API_KEY}

functions:
  hello:
    handler: handler.hello
