# objective: create a fluentd instance that utilizes an environment variable

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.hostname = "fluentd"
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "./fluentd_use_environment_variable.sh"

end
