vagrantfile_api_version = 2

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'bento/centos-7.2'
  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = './ansible/playbook.yml'
  end

  config.vm.network :forwarded_port, host: 8080, guest: 80

end
