vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/wily64'
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
end
  config.vm.provision(:shell, path: './install_newrelic_cloudwatch_agent.sh')

end
