# objective: create a vagrant image running logstash and provisioned by ansible

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'bento/centos-7.2'
  config.vm.network 'private_network', ip: '192.168.2.5'
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "./ansible/playbook.yml"
  end
  config.vm.hostname = 'ansible'

end
