vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/wily64'
  config.vm.hostname = 'nufpv'
  config.vm.network "private_network", ip: "192.168.2.2"

  config.vm.provision(:shell, path: './nginx_uwsgi_flask.sh')

end
