# objective: create a vagrant instance that runs docker

vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.hostname = "fluentd"
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "./basic_fluentd_install_centos.sh"

end
