vagrantfile_api_version = "2"

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "nagios"
  config.vm.provision "shell", path: "./nagios_basic_install.sh"
  config.vm.network "private_network", ip: "192.168.2.2"

end
