vagrantfile_api_version = 2

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision(:shell, path: "./install_conformity_monkey.sh")

end
