vagrantfile_api_version = 2

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.disksize.size = '100GB'
  config.vm.network "forwarded_port", guest: 8083, host: 8083, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
  config.vm.provision(:shell, path: './install_script.sh')
end