vagrantfile_api_version = 2

Vagrant.configure(vagrantfile_api_version) do |config|

  # in the Vagrant Box "Cloud" repository
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.12.0"
  config.vm.network "forwarded_port", guest: 8083, host: 8083, protocol: "tcp"
  config.vm.provision(:shell, path: './install_script.sh')

end