version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: cloudavail
      - run: |
          aws s3 ls


workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: AWS_Cloudavail
          filters:
            branches:
              only: initial-test-aws-cli-orb
