vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/xenial64'

  config.vm.provision(:shell, path: './selenium_python_chrome_headless.sh')

end
