vagrantfile_api_version = '2'

Vagrant.configure(vagrantfile_api_version) do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.hostname = 'mysql'
  config.vm.network 'forwarded_port', guest: 3306, host: 3306
  config.vm.provision(:shell, path: './mysql_basic_install.sh')
  # config.vm.provision 'shell', path: './logdna_config.sh', env: { LOGDNA_KEY: ENV['LOGDNA_KEY'] }

end
